// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetIndexData, GetIndexResponse, GetAuthLoginData, GetAuthLoginResponse, GetAuthCallbackData, GetAuthCallbackResponse, PostAuthLogoutData, PostAuthLogoutResponse, GetAuthMeData, GetAuthMeResponse, GetAuthMeError, ListInstancesData, ListInstancesResponse, ListInstancesError, CreateInstanceData, CreateInstanceResponse, CreateInstanceError, DeleteInstanceData, DeleteInstanceResponse, DeleteInstanceError, GetInstanceData, GetInstanceResponse, GetInstanceError, UpdateInstanceData, UpdateInstanceResponse, UpdateInstanceError, ListInstanceDomainsData, ListInstanceDomainsResponse, ListInstanceDomainsError, AddInstanceDomainData, AddInstanceDomainResponse, AddInstanceDomainError, SetPrimaryInstanceDomainData, SetPrimaryInstanceDomainResponse, SetPrimaryInstanceDomainError, RemoveInstanceDomainData, RemoveInstanceDomainResponse, RemoveInstanceDomainError, ResetInstanceLimitsData, ResetInstanceLimitsResponse, ResetInstanceLimitsError, SetInstanceLimitsData, SetInstanceLimitsResponse, SetInstanceLimitsError, CheckDomainExistsData, CheckDomainExistsResponse, CheckDomainExistsError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 * Returns the service health status.
 */
export const getIndex = <ThrowOnError extends boolean = false>(options?: Options<GetIndexData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetIndexResponse, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Begin OIDC login
 * Redirects to the Zitadel authorization endpoint (Authorization Code + PKCE).
 */
export const getAuthLogin = <ThrowOnError extends boolean = false>(options?: Options<GetAuthLoginData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAuthLoginResponse, unknown, ThrowOnError>({
        url: '/auth/login',
        ...options
    });
};

/**
 * OIDC callback
 * Exchanges the authorization code for tokens, checks the admin project role, creates a session, and redirects to the app.
 */
export const getAuthCallback = <ThrowOnError extends boolean = false>(options?: Options<GetAuthCallbackData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAuthCallbackResponse, unknown, ThrowOnError>({
        url: '/auth/callback',
        ...options
    });
};

/**
 * Log out
 * Destroys the current session and clears the session cookie.
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostAuthLogoutResponse, unknown, ThrowOnError>({
        url: '/auth/logout',
        ...options
    });
};

/**
 * Current admin user
 * Returns the authenticated admin user, or an error if not signed in.
 */
export const getAuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetAuthMeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAuthMeResponse, GetAuthMeError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/auth/me',
        ...options
    });
};

/**
 * List virtual instances
 * Lists all virtual instances on the Zitadel deployment (System API).
 */
export const listInstances = <ThrowOnError extends boolean = false>(options?: Options<ListInstancesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListInstancesResponse, ListInstancesError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/instances',
        ...options
    });
};

/**
 * Create a virtual instance
 * Creates a new Zitadel instance with its first org and an owner (human or machine). This is the only operation that requires the System API create endpoint.
 */
export const createInstance = <ThrowOnError extends boolean = false>(options: Options<CreateInstanceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateInstanceResponse, CreateInstanceError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/instances',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete a virtual instance
 * Permanently removes the instance. This may take some time on the Zitadel side.
 */
export const deleteInstance = <ThrowOnError extends boolean = false>(options: Options<DeleteInstanceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteInstanceResponse, DeleteInstanceError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/instances/{id}',
        ...options
    });
};

/**
 * Get a virtual instance
 */
export const getInstance = <ThrowOnError extends boolean = false>(options: Options<GetInstanceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetInstanceResponse, GetInstanceError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/instances/{id}',
        ...options
    });
};

/**
 * Rename a virtual instance
 * Updates the instance name. Only the name is mutable via the System API.
 */
export const updateInstance = <ThrowOnError extends boolean = false>(options: Options<UpdateInstanceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UpdateInstanceResponse, UpdateInstanceError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/instances/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * List instance domains
 */
export const listInstanceDomains = <ThrowOnError extends boolean = false>(options: Options<ListInstanceDomainsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ListInstanceDomainsResponse, ListInstanceDomainsError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/instances/{instanceId}/domains',
        ...options
    });
};

/**
 * Add a custom domain
 */
export const addInstanceDomain = <ThrowOnError extends boolean = false>(options: Options<AddInstanceDomainData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddInstanceDomainResponse, AddInstanceDomainError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/instances/{instanceId}/domains',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Set the primary domain
 */
export const setPrimaryInstanceDomain = <ThrowOnError extends boolean = false>(options: Options<SetPrimaryInstanceDomainData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<SetPrimaryInstanceDomainResponse, SetPrimaryInstanceDomainError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/instances/{instanceId}/domains/_set_primary',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Remove a custom domain
 */
export const removeInstanceDomain = <ThrowOnError extends boolean = false>(options: Options<RemoveInstanceDomainData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<RemoveInstanceDomainResponse, RemoveInstanceDomainError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/instances/{instanceId}/domains/{domain}',
        ...options
    });
};

/**
 * Reset instance limits
 */
export const resetInstanceLimits = <ThrowOnError extends boolean = false>(options: Options<ResetInstanceLimitsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<ResetInstanceLimitsResponse, ResetInstanceLimitsError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/instances/{instanceId}/limits',
        ...options
    });
};

/**
 * Set instance limits
 * Set the audit-log retention and/or the block flag for an instance. `block: true` blocks the instance.
 */
export const setInstanceLimits = <ThrowOnError extends boolean = false>(options: Options<SetInstanceLimitsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<SetInstanceLimitsResponse, SetInstanceLimitsError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/instances/{instanceId}/limits',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Check domain availability
 * Returns whether a domain is already in use by any virtual instance.
 */
export const checkDomainExists = <ThrowOnError extends boolean = false>(options: Options<CheckDomainExistsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CheckDomainExistsResponse, CheckDomainExistsError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/domains/{domain}/_exists',
        ...options
    });
};