// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteInstancesByIdData, DeleteInstancesByIdErrors, DeleteInstancesByIdResponses, DeleteInstancesByInstanceIdDomainsByDomainData, DeleteInstancesByInstanceIdDomainsByDomainErrors, DeleteInstancesByInstanceIdDomainsByDomainResponses, DeleteInstancesByInstanceIdLimitsData, DeleteInstancesByInstanceIdLimitsErrors, DeleteInstancesByInstanceIdLimitsResponses, GetAuthCallbackData, GetAuthLoginData, GetAuthMeData, GetAuthMeErrors, GetAuthMeResponses, GetAuthMethodsData, GetAuthMethodsResponses, GetDomainsByDomainExistsData, GetDomainsByDomainExistsErrors, GetDomainsByDomainExistsResponses, GetIndexData, GetIndexResponses, GetInstancesByIdData, GetInstancesByIdErrors, GetInstancesByIdResponses, GetInstancesByInstanceIdDomainsData, GetInstancesByInstanceIdDomainsErrors, GetInstancesByInstanceIdDomainsResponses, GetInstancesData, GetInstancesErrors, GetInstancesResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PostAuthLogoutData, PostAuthLogoutResponses, PostInstancesByInstanceIdDomainsData, PostInstancesByInstanceIdDomainsErrors, PostInstancesByInstanceIdDomainsResponses, PostInstancesByInstanceIdDomainsSetPrimaryData, PostInstancesByInstanceIdDomainsSetPrimaryErrors, PostInstancesByInstanceIdDomainsSetPrimaryResponses, PostInstancesData, PostInstancesErrors, PostInstancesResponses, PutInstancesByIdData, PutInstancesByIdErrors, PutInstancesByIdResponses, PutInstancesByInstanceIdLimitsData, PutInstancesByInstanceIdLimitsErrors, PutInstancesByInstanceIdLimitsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health check
 *
 * Returns the service health status.
 */
export const getIndex = <ThrowOnError extends boolean = false>(options?: Options<GetIndexData, ThrowOnError>): RequestResult<GetIndexResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetIndexResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Begin OIDC login
 *
 * Redirects to the Zitadel authorization endpoint (Authorization Code + PKCE).
 */
export const getAuthLogin = <ThrowOnError extends boolean = false>(options?: Options<GetAuthLoginData, ThrowOnError>): RequestResult<unknown, unknown, ThrowOnError> => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/auth/login', ...options });

/**
 * Static fallback login
 *
 * Authenticates the env-configured static admin account (LAVIAC_STATIC_AUTH_USERNAME / LAVIAC_STATIC_AUTH_PASSWORD_HASH). Only available when a password hash is configured; rate-limited.
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>): RequestResult<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError> => (options.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * OIDC callback
 *
 * Exchanges the authorization code for tokens, checks the admin project role, creates a session, and redirects to the app.
 */
export const getAuthCallback = <ThrowOnError extends boolean = false>(options?: Options<GetAuthCallbackData, ThrowOnError>): RequestResult<unknown, unknown, ThrowOnError> => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/auth/callback', ...options });

/**
 * Available authentication methods
 *
 * Reports which login methods are configured, so the login page can render the right forms.
 */
export const getAuthMethods = <ThrowOnError extends boolean = false>(options?: Options<GetAuthMethodsData, ThrowOnError>): RequestResult<GetAuthMethodsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAuthMethodsResponses, unknown, ThrowOnError>({ url: '/auth/methods', ...options });

/**
 * Log out
 *
 * Destroys the current session and clears the session cookie.
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>): RequestResult<PostAuthLogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostAuthLogoutResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/logout',
    ...options
});

/**
 * Current admin user
 *
 * Returns the authenticated admin user, or an error if not signed in.
 */
export const getAuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetAuthMeData, ThrowOnError>): RequestResult<GetAuthMeResponses, GetAuthMeErrors, ThrowOnError> => (options?.client ?? client).get<GetAuthMeResponses, GetAuthMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/me',
    ...options
});

/**
 * List virtual instances
 *
 * Lists all virtual instances on the Zitadel deployment (System API).
 */
export const getInstances = <ThrowOnError extends boolean = false>(options?: Options<GetInstancesData, ThrowOnError>): RequestResult<GetInstancesResponses, GetInstancesErrors, ThrowOnError> => (options?.client ?? client).get<GetInstancesResponses, GetInstancesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances',
    ...options
});

/**
 * Create a virtual instance
 *
 * Creates a new Zitadel instance with its first org and an owner (human or machine). This is the only operation that requires the System API create endpoint.
 */
export const postInstances = <ThrowOnError extends boolean = false>(options: Options<PostInstancesData, ThrowOnError>): RequestResult<PostInstancesResponses, PostInstancesErrors, ThrowOnError> => (options.client ?? client).post<PostInstancesResponses, PostInstancesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a virtual instance
 *
 * Permanently removes the instance. This may take some time on the Zitadel side.
 */
export const deleteInstancesById = <ThrowOnError extends boolean = false>(options: Options<DeleteInstancesByIdData, ThrowOnError>): RequestResult<DeleteInstancesByIdResponses, DeleteInstancesByIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteInstancesByIdResponses, DeleteInstancesByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances/{id}',
    ...options
});

/**
 * Get a virtual instance
 */
export const getInstancesById = <ThrowOnError extends boolean = false>(options: Options<GetInstancesByIdData, ThrowOnError>): RequestResult<GetInstancesByIdResponses, GetInstancesByIdErrors, ThrowOnError> => (options.client ?? client).get<GetInstancesByIdResponses, GetInstancesByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances/{id}',
    ...options
});

/**
 * Rename a virtual instance
 *
 * Updates the instance name. Only the name is mutable via the System API.
 */
export const putInstancesById = <ThrowOnError extends boolean = false>(options: Options<PutInstancesByIdData, ThrowOnError>): RequestResult<PutInstancesByIdResponses, PutInstancesByIdErrors, ThrowOnError> => (options.client ?? client).put<PutInstancesByIdResponses, PutInstancesByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List instance domains
 */
export const getInstancesByInstanceIdDomains = <ThrowOnError extends boolean = false>(options: Options<GetInstancesByInstanceIdDomainsData, ThrowOnError>): RequestResult<GetInstancesByInstanceIdDomainsResponses, GetInstancesByInstanceIdDomainsErrors, ThrowOnError> => (options.client ?? client).get<GetInstancesByInstanceIdDomainsResponses, GetInstancesByInstanceIdDomainsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances/{instanceId}/domains',
    ...options
});

/**
 * Add a custom domain
 */
export const postInstancesByInstanceIdDomains = <ThrowOnError extends boolean = false>(options: Options<PostInstancesByInstanceIdDomainsData, ThrowOnError>): RequestResult<PostInstancesByInstanceIdDomainsResponses, PostInstancesByInstanceIdDomainsErrors, ThrowOnError> => (options.client ?? client).post<PostInstancesByInstanceIdDomainsResponses, PostInstancesByInstanceIdDomainsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances/{instanceId}/domains',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Set the primary domain
 */
export const postInstancesByInstanceIdDomainsSetPrimary = <ThrowOnError extends boolean = false>(options: Options<PostInstancesByInstanceIdDomainsSetPrimaryData, ThrowOnError>): RequestResult<PostInstancesByInstanceIdDomainsSetPrimaryResponses, PostInstancesByInstanceIdDomainsSetPrimaryErrors, ThrowOnError> => (options.client ?? client).post<PostInstancesByInstanceIdDomainsSetPrimaryResponses, PostInstancesByInstanceIdDomainsSetPrimaryErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances/{instanceId}/domains/_set_primary',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove a custom domain
 */
export const deleteInstancesByInstanceIdDomainsByDomain = <ThrowOnError extends boolean = false>(options: Options<DeleteInstancesByInstanceIdDomainsByDomainData, ThrowOnError>): RequestResult<DeleteInstancesByInstanceIdDomainsByDomainResponses, DeleteInstancesByInstanceIdDomainsByDomainErrors, ThrowOnError> => (options.client ?? client).delete<DeleteInstancesByInstanceIdDomainsByDomainResponses, DeleteInstancesByInstanceIdDomainsByDomainErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances/{instanceId}/domains/{domain}',
    ...options
});

/**
 * Reset instance limits
 */
export const deleteInstancesByInstanceIdLimits = <ThrowOnError extends boolean = false>(options: Options<DeleteInstancesByInstanceIdLimitsData, ThrowOnError>): RequestResult<DeleteInstancesByInstanceIdLimitsResponses, DeleteInstancesByInstanceIdLimitsErrors, ThrowOnError> => (options.client ?? client).delete<DeleteInstancesByInstanceIdLimitsResponses, DeleteInstancesByInstanceIdLimitsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances/{instanceId}/limits',
    ...options
});

/**
 * Set instance limits
 *
 * Set the audit-log retention and/or the block flag for an instance. `block: true` blocks the instance.
 */
export const putInstancesByInstanceIdLimits = <ThrowOnError extends boolean = false>(options: Options<PutInstancesByInstanceIdLimitsData, ThrowOnError>): RequestResult<PutInstancesByInstanceIdLimitsResponses, PutInstancesByInstanceIdLimitsErrors, ThrowOnError> => (options.client ?? client).put<PutInstancesByInstanceIdLimitsResponses, PutInstancesByInstanceIdLimitsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/instances/{instanceId}/limits',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Check domain availability
 *
 * Returns whether a domain is already in use by any virtual instance.
 */
export const getDomainsByDomainExists = <ThrowOnError extends boolean = false>(options: Options<GetDomainsByDomainExistsData, ThrowOnError>): RequestResult<GetDomainsByDomainExistsResponses, GetDomainsByDomainExistsErrors, ThrowOnError> => (options.client ?? client).get<GetDomainsByDomainExistsResponses, GetDomainsByDomainExistsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/domains/{domain}/_exists',
    ...options
});
