// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}/api/v1` | (string & {});
};

export type GetIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetIndexResponses = {
    /**
     * Service is healthy
     */
    200: {
        success: true;
        code: 200;
        message: 'Service is healthy';
        data: {
            status: 'ok';
            uptime: number;
        };
    };
};

export type GetIndexResponse = GetIndexResponses[keyof GetIndexResponses];

export type GetAuthLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type GetAuthLoginResponses = {
    /**
     * Redirect to Zitadel
     */
    200: {
        success: true;
        code: 200;
        message: 'Redirect to Zitadel';
        data: null;
    };
};

export type GetAuthLoginResponse = GetAuthLoginResponses[keyof GetAuthLoginResponses];

export type GetAuthCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/callback';
};

export type GetAuthCallbackResponses = {
    /**
     * Session created
     */
    200: {
        success: true;
        code: 200;
        message: 'Session created';
        data: null;
    };
};

export type GetAuthCallbackResponse = GetAuthCallbackResponses[keyof GetAuthCallbackResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * Logout successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Logout successful';
        data: null;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeErrors = {
    /**
     * Not authenticated
     */
    401: {
        success: false;
        code: 401;
        message: 'Not authenticated';
    };
};

export type GetAuthMeError = GetAuthMeErrors[keyof GetAuthMeErrors];

export type GetAuthMeResponses = {
    /**
     * Current user
     */
    200: {
        success: true;
        code: 200;
        message: 'Current user';
        data: {
            sub: string;
            email: string | null;
            name: string | null;
            isAdmin: boolean;
        };
    };
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type GetInstancesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/instances';
};

export type GetInstancesErrors = {
    /**
     * Unauthorized: Authentication is required and has failed or has not yet been provided
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Authentication is required and has failed or has not yet been provided';
    };
    /**
     * Forbidden: You do not have permission to access the requested resource
     */
    403: {
        success: false;
        code: 403;
        message: 'Forbidden: You do not have permission to access the requested resource';
    };
};

export type GetInstancesError = GetInstancesErrors[keyof GetInstancesErrors];

export type GetInstancesResponses = {
    /**
     * Instances
     */
    200: {
        success: true;
        code: 200;
        message: 'Instances';
        data: Array<{
            id: string;
            name: string;
            state: string;
            version?: string;
            createdAt?: string;
            changedAt?: string;
            domains?: Array<{
                domain: string;
                primary?: boolean;
                generated?: boolean;
            }>;
        }>;
    };
};

export type GetInstancesResponse = GetInstancesResponses[keyof GetInstancesResponses];

export type PostInstancesData = {
    body: {
        instanceName: string;
        firstOrgName?: string;
        customDomain?: string;
        defaultLanguage?: string;
        human?: {
            userName: string;
            email: {
                email: string;
                isEmailVerified?: boolean;
            };
            profile: {
                firstName: string;
                lastName: string;
                preferredLanguage?: string;
            };
            password: {
                password: string;
                passwordChangeRequired?: boolean;
            };
        };
        machine?: {
            userName: string;
            name: string;
            personalAccessToken?: {
                expirationDate?: string;
            };
            machineKey?: {
                type: string;
                expirationDate?: string;
            };
        };
    };
    path?: never;
    query?: never;
    url: '/instances';
};

export type PostInstancesErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Instance or domain already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Instance or domain already exists';
    };
};

export type PostInstancesError = PostInstancesErrors[keyof PostInstancesErrors];

export type PostInstancesResponses = {
    /**
     * Instance created
     */
    201: {
        success: true;
        code: 201;
        message: 'Instance created';
        data: {
            instanceId: string;
            pat?: string;
            machineKey?: string;
        };
    };
};

export type PostInstancesResponse = PostInstancesResponses[keyof PostInstancesResponses];

export type DeleteInstancesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/instances/{id}';
};

export type DeleteInstancesByIdErrors = {
    /**
     * Unauthorized: Authentication is required and has failed or has not yet been provided
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Authentication is required and has failed or has not yet been provided';
    };
    /**
     * Forbidden: You do not have permission to access the requested resource
     */
    403: {
        success: false;
        code: 403;
        message: 'Forbidden: You do not have permission to access the requested resource';
    };
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type DeleteInstancesByIdError = DeleteInstancesByIdErrors[keyof DeleteInstancesByIdErrors];

export type DeleteInstancesByIdResponses = {
    /**
     * Instance deleted
     */
    200: {
        success: true;
        code: 200;
        message: 'Instance deleted';
        data: null;
    };
};

export type DeleteInstancesByIdResponse = DeleteInstancesByIdResponses[keyof DeleteInstancesByIdResponses];

export type GetInstancesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/instances/{id}';
};

export type GetInstancesByIdErrors = {
    /**
     * Unauthorized: Authentication is required and has failed or has not yet been provided
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Authentication is required and has failed or has not yet been provided';
    };
    /**
     * Forbidden: You do not have permission to access the requested resource
     */
    403: {
        success: false;
        code: 403;
        message: 'Forbidden: You do not have permission to access the requested resource';
    };
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type GetInstancesByIdError = GetInstancesByIdErrors[keyof GetInstancesByIdErrors];

export type GetInstancesByIdResponses = {
    /**
     * Instance
     */
    200: {
        success: true;
        code: 200;
        message: 'Instance';
        data: {
            id: string;
            name: string;
            state: string;
            version?: string;
            createdAt?: string;
            changedAt?: string;
            domains?: Array<{
                domain: string;
                primary?: boolean;
                generated?: boolean;
            }>;
        };
    };
};

export type GetInstancesByIdResponse = GetInstancesByIdResponses[keyof GetInstancesByIdResponses];

export type PutInstancesByIdData = {
    body: {
        instanceName: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/instances/{id}';
};

export type PutInstancesByIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type PutInstancesByIdError = PutInstancesByIdErrors[keyof PutInstancesByIdErrors];

export type PutInstancesByIdResponses = {
    /**
     * Instance updated
     */
    200: {
        success: true;
        code: 200;
        message: 'Instance updated';
        data: {
            id: string;
            name: string;
            state: string;
            version?: string;
            createdAt?: string;
            changedAt?: string;
            domains?: Array<{
                domain: string;
                primary?: boolean;
                generated?: boolean;
            }>;
        };
    };
};

export type PutInstancesByIdResponse = PutInstancesByIdResponses[keyof PutInstancesByIdResponses];

export type GetInstancesByInstanceIdDomainsData = {
    body?: never;
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}/domains';
};

export type GetInstancesByInstanceIdDomainsErrors = {
    /**
     * Unauthorized: Authentication is required and has failed or has not yet been provided
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Authentication is required and has failed or has not yet been provided';
    };
    /**
     * Forbidden: You do not have permission to access the requested resource
     */
    403: {
        success: false;
        code: 403;
        message: 'Forbidden: You do not have permission to access the requested resource';
    };
};

export type GetInstancesByInstanceIdDomainsError = GetInstancesByInstanceIdDomainsErrors[keyof GetInstancesByInstanceIdDomainsErrors];

export type GetInstancesByInstanceIdDomainsResponses = {
    /**
     * Domains
     */
    200: {
        success: true;
        code: 200;
        message: 'Domains';
        data: Array<{
            domain: string;
            primary?: boolean;
            generated?: boolean;
        }>;
    };
};

export type GetInstancesByInstanceIdDomainsResponse = GetInstancesByInstanceIdDomainsResponses[keyof GetInstancesByInstanceIdDomainsResponses];

export type PostInstancesByInstanceIdDomainsData = {
    body: {
        domain: string;
    };
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}/domains';
};

export type PostInstancesByInstanceIdDomainsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Domain already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Domain already exists';
    };
};

export type PostInstancesByInstanceIdDomainsError = PostInstancesByInstanceIdDomainsErrors[keyof PostInstancesByInstanceIdDomainsErrors];

export type PostInstancesByInstanceIdDomainsResponses = {
    /**
     * Domain added
     */
    201: {
        success: true;
        code: 201;
        message: 'Domain added';
        data: null;
    };
};

export type PostInstancesByInstanceIdDomainsResponse = PostInstancesByInstanceIdDomainsResponses[keyof PostInstancesByInstanceIdDomainsResponses];

export type PostInstancesByInstanceIdDomainsSetPrimaryData = {
    body: {
        domain: string;
    };
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}/domains/_set_primary';
};

export type PostInstancesByInstanceIdDomainsSetPrimaryErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Domain not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Domain not found';
    };
};

export type PostInstancesByInstanceIdDomainsSetPrimaryError = PostInstancesByInstanceIdDomainsSetPrimaryErrors[keyof PostInstancesByInstanceIdDomainsSetPrimaryErrors];

export type PostInstancesByInstanceIdDomainsSetPrimaryResponses = {
    /**
     * Primary domain updated
     */
    200: {
        success: true;
        code: 200;
        message: 'Primary domain updated';
        data: null;
    };
};

export type PostInstancesByInstanceIdDomainsSetPrimaryResponse = PostInstancesByInstanceIdDomainsSetPrimaryResponses[keyof PostInstancesByInstanceIdDomainsSetPrimaryResponses];

export type DeleteInstancesByInstanceIdDomainsByDomainData = {
    body?: never;
    path: {
        instanceId: string;
        domain: string;
    };
    query?: never;
    url: '/instances/{instanceId}/domains/{domain}';
};

export type DeleteInstancesByInstanceIdDomainsByDomainErrors = {
    /**
     * Domain not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Domain not found';
    };
};

export type DeleteInstancesByInstanceIdDomainsByDomainError = DeleteInstancesByInstanceIdDomainsByDomainErrors[keyof DeleteInstancesByInstanceIdDomainsByDomainErrors];

export type DeleteInstancesByInstanceIdDomainsByDomainResponses = {
    /**
     * Domain removed
     */
    200: {
        success: true;
        code: 200;
        message: 'Domain removed';
        data: null;
    };
};

export type DeleteInstancesByInstanceIdDomainsByDomainResponse = DeleteInstancesByInstanceIdDomainsByDomainResponses[keyof DeleteInstancesByInstanceIdDomainsByDomainResponses];

export type DeleteInstancesByInstanceIdLimitsData = {
    body?: never;
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}/limits';
};

export type DeleteInstancesByInstanceIdLimitsErrors = {
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type DeleteInstancesByInstanceIdLimitsError = DeleteInstancesByInstanceIdLimitsErrors[keyof DeleteInstancesByInstanceIdLimitsErrors];

export type DeleteInstancesByInstanceIdLimitsResponses = {
    /**
     * Limits reset
     */
    200: {
        success: true;
        code: 200;
        message: 'Limits reset';
        data: null;
    };
};

export type DeleteInstancesByInstanceIdLimitsResponse = DeleteInstancesByInstanceIdLimitsResponses[keyof DeleteInstancesByInstanceIdLimitsResponses];

export type PutInstancesByInstanceIdLimitsData = {
    body: {
        auditLogRetention?: string;
        block?: boolean | null;
    };
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}/limits';
};

export type PutInstancesByInstanceIdLimitsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type PutInstancesByInstanceIdLimitsError = PutInstancesByInstanceIdLimitsErrors[keyof PutInstancesByInstanceIdLimitsErrors];

export type PutInstancesByInstanceIdLimitsResponses = {
    /**
     * Limits updated
     */
    200: {
        success: true;
        code: 200;
        message: 'Limits updated';
        data: null;
    };
};

export type PutInstancesByInstanceIdLimitsResponse = PutInstancesByInstanceIdLimitsResponses[keyof PutInstancesByInstanceIdLimitsResponses];

export type PostDomainsByDomainExistsData = {
    body?: never;
    path: {
        domain: string;
    };
    query?: never;
    url: '/domains/{domain}/_exists';
};

export type PostDomainsByDomainExistsErrors = {
    /**
     * Unauthorized: Authentication is required and has failed or has not yet been provided
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Authentication is required and has failed or has not yet been provided';
    };
    /**
     * Forbidden: You do not have permission to access the requested resource
     */
    403: {
        success: false;
        code: 403;
        message: 'Forbidden: You do not have permission to access the requested resource';
    };
};

export type PostDomainsByDomainExistsError = PostDomainsByDomainExistsErrors[keyof PostDomainsByDomainExistsErrors];

export type PostDomainsByDomainExistsResponses = {
    /**
     * Domain availability
     */
    200: {
        success: true;
        code: 200;
        message: 'Domain availability';
        data: {
            exists: boolean;
        };
    };
};

export type PostDomainsByDomainExistsResponse = PostDomainsByDomainExistsResponses[keyof PostDomainsByDomainExistsResponses];
