// This file is auto-generated by @hey-api/openapi-ts

export type GetIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetIndexResponses = {
    /**
     * Service is healthy
     */
    200: {
        success: true;
        code: 200;
        message: 'Service is healthy';
        data: {
            status: 'ok';
            uptime: number;
        };
    };
};

export type GetIndexResponse = GetIndexResponses[keyof GetIndexResponses];

export type GetAuthLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type GetAuthLoginResponses = {
    /**
     * Redirect to Zitadel
     */
    200: {
        success: true;
        code: 200;
        message: 'Redirect to Zitadel';
        data: null;
    };
};

export type GetAuthLoginResponse = GetAuthLoginResponses[keyof GetAuthLoginResponses];

export type GetAuthCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/callback';
};

export type GetAuthCallbackResponses = {
    /**
     * Session created
     */
    200: {
        success: true;
        code: 200;
        message: 'Session created';
        data: null;
    };
};

export type GetAuthCallbackResponse = GetAuthCallbackResponses[keyof GetAuthCallbackResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * Logout successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Logout successful';
        data: null;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeErrors = {
    /**
     * Not authenticated
     */
    401: {
        success: false;
        code: 401;
        message: 'Not authenticated';
    };
};

export type GetAuthMeError = GetAuthMeErrors[keyof GetAuthMeErrors];

export type GetAuthMeResponses = {
    /**
     * Current user
     */
    200: {
        success: true;
        code: 200;
        message: 'Current user';
        data: {
            sub: string;
            email: string | null;
            name: string | null;
            isAdmin: boolean;
        };
    };
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type ListInstancesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/instances';
};

export type ListInstancesErrors = {
    /**
     * Unauthorized: Authentication is required and has failed or has not yet been provided
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Authentication is required and has failed or has not yet been provided';
    };
    /**
     * Forbidden: You do not have permission to access the requested resource
     */
    403: {
        success: false;
        code: 403;
        message: 'Forbidden: You do not have permission to access the requested resource';
    };
};

export type ListInstancesError = ListInstancesErrors[keyof ListInstancesErrors];

export type ListInstancesResponses = {
    /**
     * Instances
     */
    200: {
        success: true;
        code: 200;
        message: 'Instances';
        data: Array<{
            id: string;
            name: string;
            state: string;
            version?: string;
            createdAt?: string;
            changedAt?: string;
            domains?: Array<{
                domain: string;
                primary?: boolean;
                generated?: boolean;
            }>;
        }>;
    };
};

export type ListInstancesResponse = ListInstancesResponses[keyof ListInstancesResponses];

export type CreateInstanceData = {
    body: {
        instanceName: string;
        firstOrgName?: string;
        customDomain?: string;
        defaultLanguage?: string;
        human?: {
            userName: string;
            email: {
                email: string;
                isEmailVerified?: boolean;
            };
            profile: {
                firstName: string;
                lastName: string;
                preferredLanguage?: string;
            };
            password: {
                password: string;
                passwordChangeRequired?: boolean;
            };
        };
        machine?: {
            userName: string;
            name: string;
            personalAccessToken?: {
                expirationDate?: string;
            };
            machineKey?: {
                type: string;
                expirationDate?: string;
            };
        };
    };
    path?: never;
    query?: never;
    url: '/instances';
};

export type CreateInstanceErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Instance or domain already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Instance or domain already exists';
    };
};

export type CreateInstanceError = CreateInstanceErrors[keyof CreateInstanceErrors];

export type CreateInstanceResponses = {
    /**
     * Instance created
     */
    201: {
        success: true;
        code: 201;
        message: 'Instance created';
        data: {
            instanceId: string;
            pat?: string;
            machineKey?: string;
        };
    };
};

export type CreateInstanceResponse = CreateInstanceResponses[keyof CreateInstanceResponses];

export type DeleteInstanceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/instances/{id}';
};

export type DeleteInstanceErrors = {
    /**
     * Unauthorized: Authentication is required and has failed or has not yet been provided
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Authentication is required and has failed or has not yet been provided';
    };
    /**
     * Forbidden: You do not have permission to access the requested resource
     */
    403: {
        success: false;
        code: 403;
        message: 'Forbidden: You do not have permission to access the requested resource';
    };
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type DeleteInstanceError = DeleteInstanceErrors[keyof DeleteInstanceErrors];

export type DeleteInstanceResponses = {
    /**
     * Instance deleted
     */
    200: {
        success: true;
        code: 200;
        message: 'Instance deleted';
        data: null;
    };
};

export type DeleteInstanceResponse = DeleteInstanceResponses[keyof DeleteInstanceResponses];

export type GetInstanceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/instances/{id}';
};

export type GetInstanceErrors = {
    /**
     * Unauthorized: Authentication is required and has failed or has not yet been provided
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Authentication is required and has failed or has not yet been provided';
    };
    /**
     * Forbidden: You do not have permission to access the requested resource
     */
    403: {
        success: false;
        code: 403;
        message: 'Forbidden: You do not have permission to access the requested resource';
    };
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type GetInstanceError = GetInstanceErrors[keyof GetInstanceErrors];

export type GetInstanceResponses = {
    /**
     * Instance
     */
    200: {
        success: true;
        code: 200;
        message: 'Instance';
        data: {
            id: string;
            name: string;
            state: string;
            version?: string;
            createdAt?: string;
            changedAt?: string;
            domains?: Array<{
                domain: string;
                primary?: boolean;
                generated?: boolean;
            }>;
        };
    };
};

export type GetInstanceResponse = GetInstanceResponses[keyof GetInstanceResponses];

export type UpdateInstanceData = {
    body: {
        instanceName: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/instances/{id}';
};

export type UpdateInstanceErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type UpdateInstanceError = UpdateInstanceErrors[keyof UpdateInstanceErrors];

export type UpdateInstanceResponses = {
    /**
     * Instance updated
     */
    200: {
        success: true;
        code: 200;
        message: 'Instance updated';
        data: {
            id: string;
            name: string;
            state: string;
            version?: string;
            createdAt?: string;
            changedAt?: string;
            domains?: Array<{
                domain: string;
                primary?: boolean;
                generated?: boolean;
            }>;
        };
    };
};

export type UpdateInstanceResponse = UpdateInstanceResponses[keyof UpdateInstanceResponses];

export type ListInstanceDomainsData = {
    body?: never;
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}/domains';
};

export type ListInstanceDomainsErrors = {
    /**
     * Unauthorized: Authentication is required and has failed or has not yet been provided
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Authentication is required and has failed or has not yet been provided';
    };
    /**
     * Forbidden: You do not have permission to access the requested resource
     */
    403: {
        success: false;
        code: 403;
        message: 'Forbidden: You do not have permission to access the requested resource';
    };
};

export type ListInstanceDomainsError = ListInstanceDomainsErrors[keyof ListInstanceDomainsErrors];

export type ListInstanceDomainsResponses = {
    /**
     * Domains
     */
    200: {
        success: true;
        code: 200;
        message: 'Domains';
        data: Array<{
            domain: string;
            primary?: boolean;
            generated?: boolean;
        }>;
    };
};

export type ListInstanceDomainsResponse = ListInstanceDomainsResponses[keyof ListInstanceDomainsResponses];

export type AddInstanceDomainData = {
    body: {
        domain: string;
    };
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}/domains';
};

export type AddInstanceDomainErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Domain already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Domain already exists';
    };
};

export type AddInstanceDomainError = AddInstanceDomainErrors[keyof AddInstanceDomainErrors];

export type AddInstanceDomainResponses = {
    /**
     * Domain added
     */
    201: {
        success: true;
        code: 201;
        message: 'Domain added';
        data: null;
    };
};

export type AddInstanceDomainResponse = AddInstanceDomainResponses[keyof AddInstanceDomainResponses];

export type SetPrimaryInstanceDomainData = {
    body: {
        domain: string;
    };
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}/domains/_set_primary';
};

export type SetPrimaryInstanceDomainErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Domain not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Domain not found';
    };
};

export type SetPrimaryInstanceDomainError = SetPrimaryInstanceDomainErrors[keyof SetPrimaryInstanceDomainErrors];

export type SetPrimaryInstanceDomainResponses = {
    /**
     * Primary domain updated
     */
    200: {
        success: true;
        code: 200;
        message: 'Primary domain updated';
        data: null;
    };
};

export type SetPrimaryInstanceDomainResponse = SetPrimaryInstanceDomainResponses[keyof SetPrimaryInstanceDomainResponses];

export type RemoveInstanceDomainData = {
    body?: never;
    path: {
        instanceId: string;
        domain: string;
    };
    query?: never;
    url: '/instances/{instanceId}/domains/{domain}';
};

export type RemoveInstanceDomainErrors = {
    /**
     * Domain not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Domain not found';
    };
};

export type RemoveInstanceDomainError = RemoveInstanceDomainErrors[keyof RemoveInstanceDomainErrors];

export type RemoveInstanceDomainResponses = {
    /**
     * Domain removed
     */
    200: {
        success: true;
        code: 200;
        message: 'Domain removed';
        data: null;
    };
};

export type RemoveInstanceDomainResponse = RemoveInstanceDomainResponses[keyof RemoveInstanceDomainResponses];

export type ResetInstanceLimitsData = {
    body?: never;
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}/limits';
};

export type ResetInstanceLimitsErrors = {
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type ResetInstanceLimitsError = ResetInstanceLimitsErrors[keyof ResetInstanceLimitsErrors];

export type ResetInstanceLimitsResponses = {
    /**
     * Limits reset
     */
    200: {
        success: true;
        code: 200;
        message: 'Limits reset';
        data: null;
    };
};

export type ResetInstanceLimitsResponse = ResetInstanceLimitsResponses[keyof ResetInstanceLimitsResponses];

export type SetInstanceLimitsData = {
    body: {
        auditLogRetention?: string;
        block?: boolean | null;
    };
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}/limits';
};

export type SetInstanceLimitsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type SetInstanceLimitsError = SetInstanceLimitsErrors[keyof SetInstanceLimitsErrors];

export type SetInstanceLimitsResponses = {
    /**
     * Limits updated
     */
    200: {
        success: true;
        code: 200;
        message: 'Limits updated';
        data: null;
    };
};

export type SetInstanceLimitsResponse = SetInstanceLimitsResponses[keyof SetInstanceLimitsResponses];

export type CheckDomainExistsData = {
    body?: never;
    path: {
        domain: string;
    };
    query?: never;
    url: '/domains/{domain}/_exists';
};

export type CheckDomainExistsErrors = {
    /**
     * Unauthorized: Authentication is required and has failed or has not yet been provided
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Authentication is required and has failed or has not yet been provided';
    };
    /**
     * Forbidden: You do not have permission to access the requested resource
     */
    403: {
        success: false;
        code: 403;
        message: 'Forbidden: You do not have permission to access the requested resource';
    };
};

export type CheckDomainExistsError = CheckDomainExistsErrors[keyof CheckDomainExistsErrors];

export type CheckDomainExistsResponses = {
    /**
     * Domain availability
     */
    200: {
        success: true;
        code: 200;
        message: 'Domain availability';
        data: {
            exists: boolean;
        };
    };
};

export type CheckDomainExistsResponse = CheckDomainExistsResponses[keyof CheckDomainExistsResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};