// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:12191/api/v1' | 'https://laviac.is-on.net/api/v1' | (string & {});
};

export type GetAuthLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginData = {
    body: {
        username: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Unauthorized: Invalid username or password
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid username or password';
    };
    /**
     * Too many login attempts. Try again later.
     */
    429: {
        success: false;
        code: 429;
        message: 'Too many login attempts. Try again later.';
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Login successful';
        data: {
            user_sub: string;
            user_email: string | null;
            user_name: string | null;
            user_role: 'admin' | 'member';
            login_method: 'oidc' | 'static';
            created_at: number;
            expires_at: number;
            token: string;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetAuthCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/callback';
};

export type GetAuthMethodsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/methods';
};

export type GetAuthMethodsResponses = {
    /**
     * Authentication methods
     */
    200: {
        success: true;
        code: 200;
        message: 'Authentication methods';
        data: {
            oidc: boolean;
            static: boolean;
        };
    };
};

export type GetAuthMethodsResponse = GetAuthMethodsResponses[keyof GetAuthMethodsResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Logout successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Logout successful';
        data: null;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type GetAuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type GetAuthSessionErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type GetAuthSessionError = GetAuthSessionErrors[keyof GetAuthSessionErrors];

export type GetAuthSessionResponses = {
    /**
     * Session info retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Session info retrieved successfully';
        data: {
            user_sub: string;
            user_email: string | null;
            user_name: string | null;
            user_role: 'admin' | 'member';
            login_method: 'oidc' | 'static';
            created_at: number;
            expires_at: number;
        };
    };
};

export type GetAuthSessionResponse = GetAuthSessionResponses[keyof GetAuthSessionResponses];

export type GetInstancesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/instances';
};

export type GetInstancesResponses = {
    /**
     * Instances retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Instances retrieved successfully';
        data: Array<{
            id: string;
            name: string;
            state: string;
            version?: string;
            createdAt?: string;
            changedAt?: string;
            domains?: Array<{
                domain: string;
                primary?: boolean;
                generated?: boolean;
            }>;
        }>;
    };
};

export type GetInstancesResponse = GetInstancesResponses[keyof GetInstancesResponses];

export type PostInstancesData = {
    body: {
        instanceName: string;
        firstOrgName?: string;
        customDomain?: string;
        defaultLanguage?: string;
        human?: {
            userName: string;
            email: {
                email: string;
                isEmailVerified?: boolean;
            };
            profile: {
                firstName: string;
                lastName: string;
                preferredLanguage?: string;
            };
            password: {
                password: string;
                passwordChangeRequired?: boolean;
            };
        };
        machine?: {
            userName: string;
            name: string;
            personalAccessToken?: {
                expirationDate?: string;
            };
            machineKey?: {
                type: string;
                expirationDate?: string;
            };
        };
    };
    path?: never;
    query?: never;
    url: '/instances';
};

export type PostInstancesErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Conflict: Instance or domain already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Instance or domain already exists';
    };
};

export type PostInstancesError = PostInstancesErrors[keyof PostInstancesErrors];

export type PostInstancesResponses = {
    /**
     * Instance created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Instance created successfully';
        data: {
            instanceId: string;
            pat?: string;
            machineKey?: string;
            brandingTaskId: number | null;
        };
    };
};

export type PostInstancesResponse = PostInstancesResponses[keyof PostInstancesResponses];

export type DeleteInstancesByInstanceIdData = {
    body?: never;
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}';
};

export type DeleteInstancesByInstanceIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type DeleteInstancesByInstanceIdError = DeleteInstancesByInstanceIdErrors[keyof DeleteInstancesByInstanceIdErrors];

export type DeleteInstancesByInstanceIdResponses = {
    /**
     * Instance deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Instance deleted successfully';
        data: null;
    };
};

export type DeleteInstancesByInstanceIdResponse = DeleteInstancesByInstanceIdResponses[keyof DeleteInstancesByInstanceIdResponses];

export type GetInstancesByInstanceIdData = {
    body?: never;
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}';
};

export type GetInstancesByInstanceIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type GetInstancesByInstanceIdError = GetInstancesByInstanceIdErrors[keyof GetInstancesByInstanceIdErrors];

export type GetInstancesByInstanceIdResponses = {
    /**
     * Instance retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Instance retrieved successfully';
        data: {
            id: string;
            name: string;
            state: string;
            version?: string;
            createdAt?: string;
            changedAt?: string;
            domains?: Array<{
                domain: string;
                primary?: boolean;
                generated?: boolean;
            }>;
        };
    };
};

export type GetInstancesByInstanceIdResponse = GetInstancesByInstanceIdResponses[keyof GetInstancesByInstanceIdResponses];

export type PutInstancesByInstanceIdData = {
    body: {
        instanceName: string;
    };
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}';
};

export type PutInstancesByInstanceIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type PutInstancesByInstanceIdError = PutInstancesByInstanceIdErrors[keyof PutInstancesByInstanceIdErrors];

export type PutInstancesByInstanceIdResponses = {
    /**
     * Instance updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Instance updated successfully';
        data: {
            id: string;
            name: string;
            state: string;
            version?: string;
            createdAt?: string;
            changedAt?: string;
            domains?: Array<{
                domain: string;
                primary?: boolean;
                generated?: boolean;
            }>;
        };
    };
};

export type PutInstancesByInstanceIdResponse = PutInstancesByInstanceIdResponses[keyof PutInstancesByInstanceIdResponses];

export type GetInstancesByInstanceIdDomainsData = {
    body?: never;
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}/domains';
};

export type GetInstancesByInstanceIdDomainsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type GetInstancesByInstanceIdDomainsError = GetInstancesByInstanceIdDomainsErrors[keyof GetInstancesByInstanceIdDomainsErrors];

export type GetInstancesByInstanceIdDomainsResponses = {
    /**
     * Domains retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Domains retrieved successfully';
        data: Array<{
            domain: string;
            primary?: boolean;
            generated?: boolean;
        }>;
    };
};

export type GetInstancesByInstanceIdDomainsResponse = GetInstancesByInstanceIdDomainsResponses[keyof GetInstancesByInstanceIdDomainsResponses];

export type PostInstancesByInstanceIdDomainsData = {
    body: {
        domain: string;
    };
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}/domains';
};

export type PostInstancesByInstanceIdDomainsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Conflict: Domain already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Domain already exists';
    };
};

export type PostInstancesByInstanceIdDomainsError = PostInstancesByInstanceIdDomainsErrors[keyof PostInstancesByInstanceIdDomainsErrors];

export type PostInstancesByInstanceIdDomainsResponses = {
    /**
     * Domain added successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Domain added successfully';
        data: null;
    };
};

export type PostInstancesByInstanceIdDomainsResponse = PostInstancesByInstanceIdDomainsResponses[keyof PostInstancesByInstanceIdDomainsResponses];

export type PostInstancesByInstanceIdDomainsSetPrimaryData = {
    body: {
        domain: string;
    };
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}/domains/_set_primary';
};

export type PostInstancesByInstanceIdDomainsSetPrimaryErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Domain not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Domain not found';
    };
};

export type PostInstancesByInstanceIdDomainsSetPrimaryError = PostInstancesByInstanceIdDomainsSetPrimaryErrors[keyof PostInstancesByInstanceIdDomainsSetPrimaryErrors];

export type PostInstancesByInstanceIdDomainsSetPrimaryResponses = {
    /**
     * Primary domain updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Primary domain updated successfully';
        data: null;
    };
};

export type PostInstancesByInstanceIdDomainsSetPrimaryResponse = PostInstancesByInstanceIdDomainsSetPrimaryResponses[keyof PostInstancesByInstanceIdDomainsSetPrimaryResponses];

export type DeleteInstancesByInstanceIdDomainsByDomainData = {
    body?: never;
    path: {
        instanceId: string;
        domain: string;
    };
    query?: never;
    url: '/instances/{instanceId}/domains/{domain}';
};

export type DeleteInstancesByInstanceIdDomainsByDomainErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Domain not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Domain not found';
    };
};

export type DeleteInstancesByInstanceIdDomainsByDomainError = DeleteInstancesByInstanceIdDomainsByDomainErrors[keyof DeleteInstancesByInstanceIdDomainsByDomainErrors];

export type DeleteInstancesByInstanceIdDomainsByDomainResponses = {
    /**
     * Domain removed successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Domain removed successfully';
        data: null;
    };
};

export type DeleteInstancesByInstanceIdDomainsByDomainResponse = DeleteInstancesByInstanceIdDomainsByDomainResponses[keyof DeleteInstancesByInstanceIdDomainsByDomainResponses];

export type DeleteInstancesByInstanceIdLimitsData = {
    body?: never;
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}/limits';
};

export type DeleteInstancesByInstanceIdLimitsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type DeleteInstancesByInstanceIdLimitsError = DeleteInstancesByInstanceIdLimitsErrors[keyof DeleteInstancesByInstanceIdLimitsErrors];

export type DeleteInstancesByInstanceIdLimitsResponses = {
    /**
     * Limits reset successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Limits reset successfully';
        data: null;
    };
};

export type DeleteInstancesByInstanceIdLimitsResponse = DeleteInstancesByInstanceIdLimitsResponses[keyof DeleteInstancesByInstanceIdLimitsResponses];

export type PutInstancesByInstanceIdLimitsData = {
    body: {
        auditLogRetention?: string;
        block?: boolean | null;
    };
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}/limits';
};

export type PutInstancesByInstanceIdLimitsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type PutInstancesByInstanceIdLimitsError = PutInstancesByInstanceIdLimitsErrors[keyof PutInstancesByInstanceIdLimitsErrors];

export type PutInstancesByInstanceIdLimitsResponses = {
    /**
     * Limits updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Limits updated successfully';
        data: null;
    };
};

export type PutInstancesByInstanceIdLimitsResponse = PutInstancesByInstanceIdLimitsResponses[keyof PutInstancesByInstanceIdLimitsResponses];

export type GetInstancesByInstanceIdBrandingData = {
    body?: never;
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}/branding';
};

export type GetInstancesByInstanceIdBrandingErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type GetInstancesByInstanceIdBrandingError = GetInstancesByInstanceIdBrandingErrors[keyof GetInstancesByInstanceIdBrandingErrors];

export type GetInstancesByInstanceIdBrandingResponses = {
    /**
     * Branding retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Branding retrieved successfully';
        data: {
            instanceHost: string | null;
            policy: {
                primaryColor?: string;
                backgroundColor?: string;
                warnColor?: string;
                fontColor?: string;
                primaryColorDark?: string;
                backgroundColorDark?: string;
                warnColorDark?: string;
                fontColorDark?: string;
                hideLoginNameSuffix?: boolean;
                disableWatermark?: boolean;
                themeMode?: 'THEME_MODE_UNSPECIFIED' | 'THEME_MODE_AUTO' | 'THEME_MODE_DARK' | 'THEME_MODE_LIGHT';
                fontUrl?: string;
                isDefault?: boolean;
            } | null;
            error: string | null;
            defaults: {
                primaryColor?: string;
                backgroundColor?: string;
                warnColor?: string;
                fontColor?: string;
                primaryColorDark?: string;
                backgroundColorDark?: string;
                warnColorDark?: string;
                fontColorDark?: string;
                hideLoginNameSuffix?: boolean;
                disableWatermark?: boolean;
                themeMode?: 'THEME_MODE_UNSPECIFIED' | 'THEME_MODE_AUTO' | 'THEME_MODE_DARK' | 'THEME_MODE_LIGHT';
                fontUrl?: string;
                isDefault?: boolean;
            };
            defaultFont: {
                fileName: string;
                available: boolean;
            };
            lastTask: {
                id: number;
                function: string;
                created_by_user_sub: string | null;
                args: {
                    [key: string]: unknown;
                };
                storeLogs: boolean;
                status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
                created_at: number;
                finished_at: number | null;
                result: {
                    [key: string]: unknown;
                } | null;
                message: string | null;
            } | null;
        };
    };
};

export type GetInstancesByInstanceIdBrandingResponse = GetInstancesByInstanceIdBrandingResponses[keyof GetInstancesByInstanceIdBrandingResponses];

export type PostInstancesByInstanceIdBrandingApplyDefaultsData = {
    body?: never;
    path: {
        instanceId: string;
    };
    query?: never;
    url: '/instances/{instanceId}/branding/_apply_defaults';
};

export type PostInstancesByInstanceIdBrandingApplyDefaultsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Instance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Instance not found';
    };
};

export type PostInstancesByInstanceIdBrandingApplyDefaultsError = PostInstancesByInstanceIdBrandingApplyDefaultsErrors[keyof PostInstancesByInstanceIdBrandingApplyDefaultsErrors];

export type PostInstancesByInstanceIdBrandingApplyDefaultsResponses = {
    /**
     * Default branding queued successfully
     */
    202: {
        success: true;
        code: 202;
        message: 'Default branding queued successfully';
        data: {
            taskId: number;
        };
    };
};

export type PostInstancesByInstanceIdBrandingApplyDefaultsResponse = PostInstancesByInstanceIdBrandingApplyDefaultsResponses[keyof PostInstancesByInstanceIdBrandingApplyDefaultsResponses];

export type GetDomainsByDomainExistsData = {
    body?: never;
    path: {
        domain: string;
    };
    query?: never;
    url: '/domains/{domain}/_exists';
};

export type GetDomainsByDomainExistsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type GetDomainsByDomainExistsError = GetDomainsByDomainExistsErrors[keyof GetDomainsByDomainExistsErrors];

export type GetDomainsByDomainExistsResponses = {
    /**
     * Domain availability retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Domain availability retrieved successfully';
        data: {
            exists: boolean;
        };
    };
};

export type GetDomainsByDomainExistsResponse = GetDomainsByDomainExistsResponses[keyof GetDomainsByDomainExistsResponses];

export type GetAdminStatisticsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/statistics';
};

export type GetAdminStatisticsResponses = {
    /**
     * Statistics retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Statistics retrieved successfully';
        data: {
            instances: {
                total: number;
                byState: Array<{
                    state: string;
                    count: number;
                }>;
                createdPerMonth: Array<{
                    month: string;
                    count: number;
                }>;
                versions: Array<{
                    version: string;
                    count: number;
                }>;
                newest: Array<{
                    id: string;
                    name: string;
                    state: string;
                    createdAt: string | null;
                }>;
            } | null;
            domains: {
                total: number;
                custom: number;
                generated: number;
                instancesWithCustomDomain: number;
            } | null;
            zitadelError: string | null;
            audit: {
                total: number;
                perDay: Array<{
                    day: string;
                    count: number;
                }>;
                topActions: Array<{
                    action: string;
                    count: number;
                }>;
            };
            sessions: {
                active: number;
            };
            tasks: {
                pending: number;
                running: number;
                failed: number;
                completed: number;
            };
            generatedAt: number;
        };
    };
};

export type GetAdminStatisticsResponse = GetAdminStatisticsResponses[keyof GetAdminStatisticsResponses];

export type GetAdminStatisticsUsageData = {
    body?: never;
    path?: never;
    query?: {
        refresh?: 'true' | 'false';
    };
    url: '/admin/statistics/usage';
};

export type GetAdminStatisticsUsageErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type GetAdminStatisticsUsageError = GetAdminStatisticsUsageErrors[keyof GetAdminStatisticsUsageErrors];

export type GetAdminStatisticsUsageResponses = {
    /**
     * Usage retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Usage retrieved successfully';
        data: {
            fetchedAt: number;
            cached: boolean;
            totals: {
                orgs: number;
                users: number;
                unavailable: number;
            };
            items: Array<{
                instanceId: string;
                name: string;
                state: string;
                orgs: number | null;
                users: number | null;
                error: string | null;
            }>;
        };
    };
};

export type GetAdminStatisticsUsageResponse = GetAdminStatisticsUsageResponses[keyof GetAdminStatisticsUsageResponses];

export type GetAdminHostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/host';
};

export type GetAdminHostResponses = {
    /**
     * Host status retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Host status retrieved successfully';
        data: {
            hostname: string;
            os: {
                name: string;
                version: string | null;
                id: string | null;
                prettyName: string;
            };
            kernel: string;
            arch: string;
            uptime: number;
            bootedAt: number;
            virtualization: {
                virtual: boolean;
                vendor: string | null;
                product: string | null;
            };
            containerized: boolean;
            hostRoot: string;
            cpu: {
                model: string;
                cores: number;
                loadAverage: Array<number>;
                usage: number | null;
            };
            memory: {
                total: number;
                used: number;
                available: number;
                swapTotal: number;
                swapUsed: number;
            };
            disks: Array<{
                label: string;
                path: string;
                total: number;
                used: number;
                free: number;
            }>;
            runtime: {
                bunVersion: string;
                pid: number;
                uptime: number;
                rss: number;
                databaseSize: number | null;
            };
            zitadel: {
                url: string | null;
                reachable: boolean;
                statusCode: number | null;
                latencyMs: number | null;
                error: string | null;
            };
        };
    };
};

export type GetAdminHostResponse = GetAdminHostResponses[keyof GetAdminHostResponses];

export type GetAdminHostMetricsData = {
    body?: never;
    path?: never;
    query?: {
        range?: '1h' | '24h' | '7d';
    };
    url: '/admin/host/metrics';
};

export type GetAdminHostMetricsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type GetAdminHostMetricsError = GetAdminHostMetricsErrors[keyof GetAdminHostMetricsErrors];

export type GetAdminHostMetricsResponses = {
    /**
     * Host metrics retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Host metrics retrieved successfully';
        data: {
            range: '1h' | '24h' | '7d';
            sampleInterval: number;
            points: Array<{
                timestamp: number;
                cpuUsage: number | null;
                load1: number;
                memoryUsage: number;
                diskUsage: number | null;
            }>;
        };
    };
};

export type GetAdminHostMetricsResponse = GetAdminHostMetricsResponses[keyof GetAdminHostMetricsResponses];

export type GetAdminUpdatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/updates';
};

export type GetAdminUpdatesResponses = {
    /**
     * Update status retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Update status retrieved successfully';
        data: {
            os: {
                supported: boolean;
                reason: string | null;
                checkedAt: number | null;
                listsUpdatedAt: number | null;
                rebootRequired: boolean;
                rebootPackages: Array<string>;
                packages: Array<{
                    name: string;
                    currentVersion: string;
                    candidateVersion: string;
                    origin: string;
                    security: boolean;
                }>;
                error: string | null;
            };
            zitadel: {
                latestVersion: string | null;
                latestPublishedAt: string | null;
                latestUrl: string | null;
                checkedAt: number | null;
                error: string | null;
                instanceVersions: Array<{
                    version: string;
                    count: number;
                }>;
                updateAvailable: boolean | null;
            };
        };
    };
};

export type GetAdminUpdatesResponse = GetAdminUpdatesResponses[keyof GetAdminUpdatesResponses];

export type PostAdminUpdatesCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/updates/_check';
};

export type PostAdminUpdatesCheckResponses = {
    /**
     * Update check completed successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Update check completed successfully';
        data: {
            os: {
                supported: boolean;
                reason: string | null;
                checkedAt: number | null;
                listsUpdatedAt: number | null;
                rebootRequired: boolean;
                rebootPackages: Array<string>;
                packages: Array<{
                    name: string;
                    currentVersion: string;
                    candidateVersion: string;
                    origin: string;
                    security: boolean;
                }>;
                error: string | null;
            };
            zitadel: {
                latestVersion: string | null;
                latestPublishedAt: string | null;
                latestUrl: string | null;
                checkedAt: number | null;
                error: string | null;
                instanceVersions: Array<{
                    version: string;
                    count: number;
                }>;
                updateAvailable: boolean | null;
            };
        };
    };
};

export type PostAdminUpdatesCheckResponse = PostAdminUpdatesCheckResponses[keyof PostAdminUpdatesCheckResponses];

export type GetAdminAuditData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        order?: 'newest' | 'oldest';
        searchString?: string;
        action?: string;
        instanceId?: string;
    };
    url: '/admin/audit';
};

export type GetAdminAuditErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type GetAdminAuditError = GetAdminAuditErrors[keyof GetAdminAuditErrors];

export type GetAdminAuditResponses = {
    /**
     * Audit log retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Audit log retrieved successfully';
        data: {
            total: number;
            items: Array<{
                id: number;
                actor_sub: string;
                action: string;
                target_instance_id: string | null;
                detail: string | null;
                created_at: number;
            }>;
        };
    };
};

export type GetAdminAuditResponse = GetAdminAuditResponses[keyof GetAdminAuditResponses];

export type GetAdminTasksData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/admin/tasks';
};

export type GetAdminTasksErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type GetAdminTasksError = GetAdminTasksErrors[keyof GetAdminTasksErrors];

export type GetAdminTasksResponses = {
    /**
     * Tasks retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Tasks retrieved successfully';
        data: Array<{
            id: number;
            function: string;
            created_by_user_sub: string | null;
            args: {
                [key: string]: unknown;
            };
            storeLogs: boolean;
            status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
            created_at: number;
            finished_at: number | null;
            result: {
                [key: string]: unknown;
            } | null;
            message: string | null;
        }>;
    };
};

export type GetAdminTasksResponse = GetAdminTasksResponses[keyof GetAdminTasksResponses];

export type GetAdminTasksByTaskIdData = {
    body?: never;
    path: {
        taskId: number;
    };
    query?: never;
    url: '/admin/tasks/{taskId}';
};

export type GetAdminTasksByTaskIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Task not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Task not found';
    };
};

export type GetAdminTasksByTaskIdError = GetAdminTasksByTaskIdErrors[keyof GetAdminTasksByTaskIdErrors];

export type GetAdminTasksByTaskIdResponses = {
    /**
     * Task retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Task retrieved successfully';
        data: {
            id: number;
            function: string;
            created_by_user_sub: string | null;
            args: {
                [key: string]: unknown;
            };
            storeLogs: boolean;
            status: 'pending' | 'running' | 'paused' | 'failed' | 'completed';
            created_at: number;
            finished_at: number | null;
            result: {
                [key: string]: unknown;
            } | null;
            message: string | null;
            logs: string | null;
        };
    };
};

export type GetAdminTasksByTaskIdResponse = GetAdminTasksByTaskIdResponses[keyof GetAdminTasksByTaskIdResponses];

export type GetAdminSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/sessions';
};

export type GetAdminSessionsResponses = {
    /**
     * Sessions retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Sessions retrieved successfully';
        data: Array<{
            id: string;
            user_sub: string;
            user_email: string | null;
            user_name: string | null;
            user_role: 'admin' | 'member';
            login_method: 'oidc' | 'static';
            created_at: number;
            expires_at: number;
            current: boolean;
        }>;
    };
};

export type GetAdminSessionsResponse = GetAdminSessionsResponses[keyof GetAdminSessionsResponses];

export type DeleteAdminSessionsBySessionIdData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/admin/sessions/{sessionId}';
};

export type DeleteAdminSessionsBySessionIdErrors = {
    /**
     * Bad Request: Use logout to end your own session
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Use logout to end your own session';
    };
    /**
     * Session not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Session not found';
    };
};

export type DeleteAdminSessionsBySessionIdError = DeleteAdminSessionsBySessionIdErrors[keyof DeleteAdminSessionsBySessionIdErrors];

export type DeleteAdminSessionsBySessionIdResponses = {
    /**
     * Session revoked successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Session revoked successfully';
        data: null;
    };
};

export type DeleteAdminSessionsBySessionIdResponse = DeleteAdminSessionsBySessionIdResponses[keyof DeleteAdminSessionsBySessionIdResponses];
