// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Service is healthy
 */
export const zGetHealthResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Service is healthy'),
    data: z.object({
        status: z.literal('ok'),
        uptime: z.number()
    })
});

export const zPostAuthLoginBody = z.object({
    username: z.string().min(1),
    password: z.string().min(1)
});

/**
 * Login successful
 */
export const zPostAuthLoginResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Login successful'),
    data: z.object({
        token: z.string(),
        user_sub: z.string(),
        user_email: z.string().nullable(),
        user_name: z.string().nullable(),
        user_role: z.enum(['admin', 'member']),
        login_method: z.enum(['oidc', 'static']),
        created_at: z.number(),
        expires_at: z.number()
    })
});

/**
 * Authentication methods
 */
export const zGetAuthMethodsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Authentication methods'),
    data: z.object({
        oidc: z.boolean(),
        static: z.boolean()
    })
});

/**
 * Logout successful
 */
export const zPostAuthLogoutResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Logout successful'),
    data: z.null()
});

/**
 * Current user
 */
export const zGetAuthMeResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Current user'),
    data: z.object({
        sub: z.string(),
        email: z.string().nullable(),
        name: z.string().nullable(),
        role: z.enum(['admin', 'member']),
        login_method: z.enum(['oidc', 'static'])
    })
});

/**
 * Instances
 */
export const zGetInstancesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Instances'),
    data: z.array(z.object({
        id: z.string(),
        name: z.string(),
        state: z.string(),
        version: z.string().optional(),
        createdAt: z.string().optional(),
        changedAt: z.string().optional(),
        domains: z.array(z.object({
            domain: z.string(),
            primary: z.boolean().optional(),
            generated: z.boolean().optional()
        })).optional()
    }))
});

export const zPostInstancesBody = z.object({
    instanceName: z.string().min(1),
    firstOrgName: z.string().optional(),
    customDomain: z.string().optional(),
    defaultLanguage: z.string().optional(),
    human: z.object({
        userName: z.string().min(1),
        email: z.object({
            email: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
            isEmailVerified: z.boolean().optional()
        }),
        profile: z.object({
            firstName: z.string().min(1),
            lastName: z.string().min(1),
            preferredLanguage: z.string().optional()
        }),
        password: z.object({
            password: z.string().min(1),
            passwordChangeRequired: z.boolean().optional()
        })
    }).optional(),
    machine: z.object({
        userName: z.string().min(1),
        name: z.string().min(1),
        personalAccessToken: z.object({
            expirationDate: z.string().optional()
        }).optional(),
        machineKey: z.object({
            type: z.string(),
            expirationDate: z.string().optional()
        }).optional()
    }).optional()
});

/**
 * Instance created
 */
export const zPostInstancesResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Instance created'),
    data: z.object({
        instanceId: z.string(),
        pat: z.string().optional(),
        machineKey: z.string().optional()
    })
});

export const zDeleteInstancesByIdPath = z.object({
    id: z.string()
});

/**
 * Instance deleted
 */
export const zDeleteInstancesByIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Instance deleted'),
    data: z.null()
});

export const zGetInstancesByIdPath = z.object({
    id: z.string()
});

/**
 * Instance
 */
export const zGetInstancesByIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Instance'),
    data: z.object({
        id: z.string(),
        name: z.string(),
        state: z.string(),
        version: z.string().optional(),
        createdAt: z.string().optional(),
        changedAt: z.string().optional(),
        domains: z.array(z.object({
            domain: z.string(),
            primary: z.boolean().optional(),
            generated: z.boolean().optional()
        })).optional()
    })
});

export const zPutInstancesByIdBody = z.object({
    instanceName: z.string().min(1)
});

export const zPutInstancesByIdPath = z.object({
    id: z.string()
});

/**
 * Instance updated
 */
export const zPutInstancesByIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Instance updated'),
    data: z.object({
        id: z.string(),
        name: z.string(),
        state: z.string(),
        version: z.string().optional(),
        createdAt: z.string().optional(),
        changedAt: z.string().optional(),
        domains: z.array(z.object({
            domain: z.string(),
            primary: z.boolean().optional(),
            generated: z.boolean().optional()
        })).optional()
    })
});

export const zGetInstancesByInstanceIdDomainsPath = z.object({
    instanceId: z.string()
});

/**
 * Domains
 */
export const zGetInstancesByInstanceIdDomainsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Domains'),
    data: z.array(z.object({
        domain: z.string(),
        primary: z.boolean().optional(),
        generated: z.boolean().optional()
    }))
});

export const zPostInstancesByInstanceIdDomainsBody = z.object({
    domain: z.string().min(1)
});

export const zPostInstancesByInstanceIdDomainsPath = z.object({
    instanceId: z.string()
});

/**
 * Domain added
 */
export const zPostInstancesByInstanceIdDomainsResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Domain added'),
    data: z.null()
});

export const zPostInstancesByInstanceIdDomainsSetPrimaryBody = z.object({
    domain: z.string().min(1)
});

export const zPostInstancesByInstanceIdDomainsSetPrimaryPath = z.object({
    instanceId: z.string()
});

/**
 * Primary domain updated
 */
export const zPostInstancesByInstanceIdDomainsSetPrimaryResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Primary domain updated'),
    data: z.null()
});

export const zDeleteInstancesByInstanceIdDomainsByDomainPath = z.object({
    instanceId: z.string(),
    domain: z.string()
});

/**
 * Domain removed
 */
export const zDeleteInstancesByInstanceIdDomainsByDomainResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Domain removed'),
    data: z.null()
});

export const zDeleteInstancesByInstanceIdLimitsPath = z.object({
    instanceId: z.string()
});

/**
 * Limits reset
 */
export const zDeleteInstancesByInstanceIdLimitsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Limits reset'),
    data: z.null()
});

export const zPutInstancesByInstanceIdLimitsBody = z.object({
    auditLogRetention: z.string().optional(),
    block: z.boolean().nullish()
});

export const zPutInstancesByInstanceIdLimitsPath = z.object({
    instanceId: z.string()
});

/**
 * Limits updated
 */
export const zPutInstancesByInstanceIdLimitsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Limits updated'),
    data: z.null()
});

export const zGetDomainsByDomainExistsPath = z.object({
    domain: z.string()
});

/**
 * Domain availability
 */
export const zGetDomainsByDomainExistsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Domain availability'),
    data: z.object({
        exists: z.boolean()
    })
});
