// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zPostAuthLoginBody = z.object({
    username: z.string(),
    password: z.string()
});

/**
 * Login successful
 */
export const zPostAuthLoginResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Login successful'),
    data: z.object({
        user_sub: z.string(),
        user_email: z.string().nullable(),
        user_name: z.string().nullable(),
        user_role: z.enum(['admin', 'member']),
        login_method: z.enum(['oidc', 'static']),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        token: z.string()
    })
});

/**
 * Authentication methods
 */
export const zGetAuthMethodsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Authentication methods'),
    data: z.object({
        oidc: z.boolean(),
        static: z.boolean()
    })
});

/**
 * Logout successful
 */
export const zPostAuthLogoutResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Logout successful'),
    data: z.null()
});

/**
 * Session info retrieved successfully
 */
export const zGetAuthSessionResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Session info retrieved successfully'),
    data: z.object({
        user_sub: z.string(),
        user_email: z.string().nullable(),
        user_name: z.string().nullable(),
        user_role: z.enum(['admin', 'member']),
        login_method: z.enum(['oidc', 'static']),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
});

/**
 * Instances retrieved successfully
 */
export const zGetInstancesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Instances retrieved successfully'),
    data: z.array(z.object({
        id: z.string(),
        name: z.string(),
        state: z.string(),
        version: z.string().optional(),
        createdAt: z.string().optional(),
        changedAt: z.string().optional(),
        domains: z.array(z.object({
            domain: z.string(),
            primary: z.boolean().optional(),
            generated: z.boolean().optional()
        })).optional(),
        template: z.enum([
            'private',
            'public-b2b-b2c',
            'public-b2c',
            'public-b2b',
            'minimal'
        ]).nullable()
    }))
});

export const zPostInstancesBody = z.object({
    instanceName: z.string().min(1),
    template: z.enum([
        'private',
        'public-b2b-b2c',
        'public-b2c',
        'public-b2b',
        'minimal'
    ]),
    templateOptions: z.object({
        homeOrgName: z.string().min(1).max(200).optional(),
        homeOrgDomain: z.string().max(200).regex(/^(?=.{1,253}$)([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/).optional(),
        allowOrgRegistration: z.boolean().optional()
    }).optional().default({}),
    customDomain: z.string().optional(),
    defaultLanguage: z.string().optional(),
    human: z.object({
        userName: z.string().min(1),
        email: z.object({
            email: z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
            isEmailVerified: z.boolean().optional()
        }),
        profile: z.object({
            firstName: z.string().min(1),
            lastName: z.string().min(1),
            preferredLanguage: z.string().optional()
        }),
        password: z.object({
            password: z.string().min(1),
            passwordChangeRequired: z.boolean().optional()
        })
    }).optional(),
    machine: z.object({
        userName: z.string().min(1),
        name: z.string().min(1),
        personalAccessToken: z.object({
            expirationDate: z.string().optional()
        }).optional(),
        machineKey: z.object({
            type: z.string(),
            expirationDate: z.string().optional()
        }).optional()
    }).optional()
});

/**
 * Instance created successfully
 */
export const zPostInstancesResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Instance created successfully'),
    data: z.object({
        instanceId: z.string(),
        pat: z.string().optional(),
        machineKey: z.string().optional(),
        templateSaved: z.boolean(),
        provisioningTaskId: z.number().nullable(),
        brandingTaskId: z.number().nullable()
    })
});

export const zDeleteInstancesByInstanceIdPath = z.object({
    instanceId: z.string().min(1).max(64)
});

/**
 * Instance deleted successfully
 */
export const zDeleteInstancesByInstanceIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Instance deleted successfully'),
    data: z.null()
});

export const zGetInstancesByInstanceIdPath = z.object({
    instanceId: z.string().min(1).max(64)
});

/**
 * Instance retrieved successfully
 */
export const zGetInstancesByInstanceIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Instance retrieved successfully'),
    data: z.object({
        id: z.string(),
        name: z.string(),
        state: z.string(),
        version: z.string().optional(),
        createdAt: z.string().optional(),
        changedAt: z.string().optional(),
        domains: z.array(z.object({
            domain: z.string(),
            primary: z.boolean().optional(),
            generated: z.boolean().optional()
        })).optional()
    })
});

export const zPutInstancesByInstanceIdBody = z.object({
    instanceName: z.string().min(1)
});

export const zPutInstancesByInstanceIdPath = z.object({
    instanceId: z.string().min(1).max(64)
});

/**
 * Instance updated successfully
 */
export const zPutInstancesByInstanceIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Instance updated successfully'),
    data: z.object({
        id: z.string(),
        name: z.string(),
        state: z.string(),
        version: z.string().optional(),
        createdAt: z.string().optional(),
        changedAt: z.string().optional(),
        domains: z.array(z.object({
            domain: z.string(),
            primary: z.boolean().optional(),
            generated: z.boolean().optional()
        })).optional()
    })
});

export const zGetInstancesByInstanceIdDomainsPath = z.object({
    instanceId: z.string().min(1).max(64)
});

/**
 * Domains retrieved successfully
 */
export const zGetInstancesByInstanceIdDomainsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Domains retrieved successfully'),
    data: z.array(z.object({
        domain: z.string(),
        primary: z.boolean().optional(),
        generated: z.boolean().optional()
    }))
});

export const zPostInstancesByInstanceIdDomainsBody = z.object({
    domain: z.string().min(1).max(253)
});

export const zPostInstancesByInstanceIdDomainsPath = z.object({
    instanceId: z.string().min(1).max(64)
});

/**
 * Domain added successfully
 */
export const zPostInstancesByInstanceIdDomainsResponse = z.object({
    success: z.literal(true),
    code: z.literal(201),
    message: z.literal('Domain added successfully'),
    data: z.null()
});

export const zPostInstancesByInstanceIdDomainsSetPrimaryBody = z.object({
    domain: z.string().min(1).max(253)
});

export const zPostInstancesByInstanceIdDomainsSetPrimaryPath = z.object({
    instanceId: z.string().min(1).max(64)
});

/**
 * Primary domain updated successfully
 */
export const zPostInstancesByInstanceIdDomainsSetPrimaryResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Primary domain updated successfully'),
    data: z.null()
});

export const zDeleteInstancesByInstanceIdDomainsByDomainPath = z.object({
    instanceId: z.string().min(1).max(64),
    domain: z.string().min(1).max(253)
});

/**
 * Domain removed successfully
 */
export const zDeleteInstancesByInstanceIdDomainsByDomainResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Domain removed successfully'),
    data: z.null()
});

export const zDeleteInstancesByInstanceIdLimitsPath = z.object({
    instanceId: z.string().min(1).max(64)
});

/**
 * Limits reset successfully
 */
export const zDeleteInstancesByInstanceIdLimitsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Limits reset successfully'),
    data: z.null()
});

export const zPutInstancesByInstanceIdLimitsBody = z.object({
    auditLogRetention: z.string().optional(),
    block: z.boolean().nullish()
});

export const zPutInstancesByInstanceIdLimitsPath = z.object({
    instanceId: z.string().min(1).max(64)
});

/**
 * Limits updated successfully
 */
export const zPutInstancesByInstanceIdLimitsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Limits updated successfully'),
    data: z.null()
});

export const zGetInstancesByInstanceIdBrandingPath = z.object({
    instanceId: z.string().min(1).max(64)
});

/**
 * Branding retrieved successfully
 */
export const zGetInstancesByInstanceIdBrandingResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Branding retrieved successfully'),
    data: z.object({
        instanceHost: z.string().nullable(),
        policy: z.object({
            primaryColor: z.string().optional(),
            backgroundColor: z.string().optional(),
            warnColor: z.string().optional(),
            fontColor: z.string().optional(),
            primaryColorDark: z.string().optional(),
            backgroundColorDark: z.string().optional(),
            warnColorDark: z.string().optional(),
            fontColorDark: z.string().optional(),
            hideLoginNameSuffix: z.boolean().optional(),
            disableWatermark: z.boolean().optional(),
            themeMode: z.enum([
                'THEME_MODE_UNSPECIFIED',
                'THEME_MODE_AUTO',
                'THEME_MODE_DARK',
                'THEME_MODE_LIGHT'
            ]).optional(),
            fontUrl: z.string().optional(),
            isDefault: z.boolean().optional()
        }).nullable(),
        error: z.string().nullable(),
        defaults: z.object({
            primaryColor: z.string().optional(),
            backgroundColor: z.string().optional(),
            warnColor: z.string().optional(),
            fontColor: z.string().optional(),
            primaryColorDark: z.string().optional(),
            backgroundColorDark: z.string().optional(),
            warnColorDark: z.string().optional(),
            fontColorDark: z.string().optional(),
            hideLoginNameSuffix: z.boolean().optional(),
            disableWatermark: z.boolean().optional(),
            themeMode: z.enum([
                'THEME_MODE_UNSPECIFIED',
                'THEME_MODE_AUTO',
                'THEME_MODE_DARK',
                'THEME_MODE_LIGHT'
            ]).optional(),
            fontUrl: z.string().optional(),
            isDefault: z.boolean().optional()
        }),
        defaultFont: z.object({
            fileName: z.string(),
            available: z.boolean()
        }),
        lastTask: z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            function: z.string(),
            created_by_user_sub: z.string().nullable(),
            args: z.record(z.string(), z.unknown()),
            storeLogs: z.boolean(),
            status: z.enum([
                'pending',
                'running',
                'paused',
                'failed',
                'completed'
            ]),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            finished_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable(),
            result: z.record(z.string(), z.unknown()).nullable(),
            message: z.string().nullable()
        }).nullable()
    })
});

export const zPostInstancesByInstanceIdBrandingApplyDefaultsPath = z.object({
    instanceId: z.string().min(1).max(64)
});

/**
 * Default branding queued successfully
 */
export const zPostInstancesByInstanceIdBrandingApplyDefaultsResponse = z.object({
    success: z.literal(true),
    code: z.literal(202),
    message: z.literal('Default branding queued successfully'),
    data: z.object({
        taskId: z.number()
    })
});

export const zGetInstancesByInstanceIdTemplatePath = z.object({
    instanceId: z.string().min(1).max(64)
});

/**
 * Template retrieved successfully
 */
export const zGetInstancesByInstanceIdTemplateResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Template retrieved successfully'),
    data: z.object({
        setup: z.object({
            template: z.object({
                id: z.enum([
                    'private',
                    'public-b2b-b2c',
                    'public-b2c',
                    'public-b2b',
                    'minimal'
                ]),
                name: z.string(),
                summary: z.string(),
                icon: z.string(),
                homeOrg: z.object({
                    kind: z.enum([
                        'company',
                        'public',
                        'catch-all'
                    ]),
                    label: z.string(),
                    description: z.string(),
                    placeholder: z.string()
                }).nullable(),
                asksOrgRegistration: z.boolean()
            }),
            options: z.object({
                homeOrgName: z.string().min(1).max(200).optional(),
                homeOrgDomain: z.string().max(200).regex(/^(?=.{1,253}$)([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/).optional(),
                allowOrgRegistration: z.boolean().optional()
            }),
            systemOrgId: z.string().nullable(),
            homeOrgId: z.string().nullable(),
            createdAt: z.number(),
            createdBySub: z.string().nullable(),
            sections: z.array(z.object({
                id: z.string(),
                title: z.string(),
                description: z.string(),
                rows: z.array(z.object({
                    label: z.string(),
                    value: z.string(),
                    source: z.enum([
                        'baseline',
                        'template',
                        'option'
                    ])
                }))
            }))
        }).nullable(),
        defaultOrg: z.object({
            id: z.string(),
            name: z.string().nullable()
        }).nullable(),
        error: z.string().nullable(),
        lastTask: z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            function: z.string(),
            created_by_user_sub: z.string().nullable(),
            args: z.record(z.string(), z.unknown()),
            storeLogs: z.boolean(),
            status: z.enum([
                'pending',
                'running',
                'paused',
                'failed',
                'completed'
            ]),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
            finished_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable(),
            result: z.record(z.string(), z.unknown()).nullable(),
            message: z.string().nullable()
        }).nullable()
    })
});

export const zPostInstancesByInstanceIdTemplateApplyPath = z.object({
    instanceId: z.string().min(1).max(64)
});

/**
 * Template queued successfully
 */
export const zPostInstancesByInstanceIdTemplateApplyResponse = z.object({
    success: z.literal(true),
    code: z.literal(202),
    message: z.literal('Template queued successfully'),
    data: z.object({
        taskId: z.number()
    })
});

/**
 * Instance templates retrieved successfully
 */
export const zGetInstanceTemplatesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Instance templates retrieved successfully'),
    data: z.object({
        systemOrgName: z.string(),
        templates: z.array(z.object({
            id: z.enum([
                'private',
                'public-b2b-b2c',
                'public-b2c',
                'public-b2b',
                'minimal'
            ]),
            name: z.string(),
            summary: z.string(),
            icon: z.string(),
            homeOrg: z.object({
                kind: z.enum([
                    'company',
                    'public',
                    'catch-all'
                ]),
                label: z.string(),
                description: z.string(),
                placeholder: z.string()
            }).nullable(),
            asksOrgRegistration: z.boolean(),
            sections: z.array(z.object({
                id: z.string(),
                title: z.string(),
                description: z.string(),
                rows: z.array(z.object({
                    label: z.string(),
                    value: z.string(),
                    source: z.enum([
                        'baseline',
                        'template',
                        'option'
                    ])
                }))
            }))
        }))
    })
});

export const zGetDomainsByDomainExistsPath = z.object({
    domain: z.string().min(1).max(253)
});

/**
 * Domain availability retrieved successfully
 */
export const zGetDomainsByDomainExistsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Domain availability retrieved successfully'),
    data: z.object({
        exists: z.boolean()
    })
});

/**
 * Statistics retrieved successfully
 */
export const zGetAdminStatisticsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Statistics retrieved successfully'),
    data: z.object({
        instances: z.object({
            total: z.number(),
            byState: z.array(z.object({
                state: z.string(),
                count: z.number()
            })),
            createdPerMonth: z.array(z.object({
                month: z.string(),
                count: z.number()
            })),
            versions: z.array(z.object({
                version: z.string(),
                count: z.number()
            })),
            newest: z.array(z.object({
                id: z.string(),
                name: z.string(),
                state: z.string(),
                createdAt: z.string().nullable()
            }))
        }).nullable(),
        domains: z.object({
            total: z.number(),
            custom: z.number(),
            generated: z.number(),
            instancesWithCustomDomain: z.number()
        }).nullable(),
        zitadelError: z.string().nullable(),
        audit: z.object({
            total: z.number(),
            perDay: z.array(z.object({
                day: z.string(),
                count: z.number()
            })),
            topActions: z.array(z.object({
                action: z.string(),
                count: z.number()
            }))
        }),
        sessions: z.object({
            active: z.number()
        }),
        tasks: z.object({
            pending: z.number(),
            running: z.number(),
            failed: z.number(),
            completed: z.number()
        }),
        generatedAt: z.number()
    })
});

export const zGetAdminStatisticsUsageQuery = z.object({
    refresh: z.enum(['true', 'false']).optional()
});

/**
 * Usage retrieved successfully
 */
export const zGetAdminStatisticsUsageResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Usage retrieved successfully'),
    data: z.object({
        fetchedAt: z.number(),
        cached: z.boolean(),
        totals: z.object({
            orgs: z.number(),
            users: z.number(),
            unavailable: z.number()
        }),
        items: z.array(z.object({
            instanceId: z.string(),
            name: z.string(),
            state: z.string(),
            orgs: z.number().nullable(),
            users: z.number().nullable(),
            error: z.string().nullable()
        }))
    })
});

/**
 * Host status retrieved successfully
 */
export const zGetAdminHostResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Host status retrieved successfully'),
    data: z.object({
        hostname: z.string(),
        os: z.object({
            name: z.string(),
            version: z.string().nullable(),
            id: z.string().nullable(),
            prettyName: z.string()
        }),
        kernel: z.string(),
        arch: z.string(),
        uptime: z.number(),
        bootedAt: z.number(),
        virtualization: z.object({
            virtual: z.boolean(),
            vendor: z.string().nullable(),
            product: z.string().nullable()
        }),
        containerized: z.boolean(),
        hostRoot: z.string(),
        cpu: z.object({
            model: z.string(),
            cores: z.number(),
            loadAverage: z.array(z.number()),
            usage: z.number().nullable()
        }),
        memory: z.object({
            total: z.number(),
            used: z.number(),
            available: z.number(),
            swapTotal: z.number(),
            swapUsed: z.number()
        }),
        disks: z.array(z.object({
            label: z.string(),
            path: z.string(),
            total: z.number(),
            used: z.number(),
            free: z.number()
        })),
        runtime: z.object({
            bunVersion: z.string(),
            pid: z.number(),
            uptime: z.number(),
            rss: z.number(),
            databaseSize: z.number().nullable()
        }),
        zitadel: z.object({
            url: z.string().nullable(),
            reachable: z.boolean(),
            statusCode: z.number().nullable(),
            latencyMs: z.number().nullable(),
            error: z.string().nullable()
        })
    })
});

export const zGetAdminHostMetricsQuery = z.object({
    range: z.enum([
        '1h',
        '24h',
        '7d'
    ]).optional().default('24h')
});

/**
 * Host metrics retrieved successfully
 */
export const zGetAdminHostMetricsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Host metrics retrieved successfully'),
    data: z.object({
        range: z.enum([
            '1h',
            '24h',
            '7d'
        ]),
        sampleInterval: z.number(),
        points: z.array(z.object({
            timestamp: z.number(),
            cpuUsage: z.number().nullable(),
            load1: z.number(),
            memoryUsage: z.number(),
            diskUsage: z.number().nullable()
        }))
    })
});

/**
 * Update status retrieved successfully
 */
export const zGetAdminUpdatesResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Update status retrieved successfully'),
    data: z.object({
        os: z.object({
            supported: z.boolean(),
            reason: z.string().nullable(),
            checkedAt: z.number().nullable(),
            listsUpdatedAt: z.number().nullable(),
            rebootRequired: z.boolean(),
            rebootPackages: z.array(z.string()),
            packages: z.array(z.object({
                name: z.string(),
                currentVersion: z.string(),
                candidateVersion: z.string(),
                origin: z.string(),
                security: z.boolean()
            })),
            error: z.string().nullable()
        }),
        zitadel: z.object({
            latestVersion: z.string().nullable(),
            latestPublishedAt: z.string().nullable(),
            latestUrl: z.string().nullable(),
            checkedAt: z.number().nullable(),
            error: z.string().nullable(),
            instanceVersions: z.array(z.object({
                version: z.string(),
                count: z.number()
            })),
            updateAvailable: z.boolean().nullable()
        })
    })
});

/**
 * Update check completed successfully
 */
export const zPostAdminUpdatesCheckResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Update check completed successfully'),
    data: z.object({
        os: z.object({
            supported: z.boolean(),
            reason: z.string().nullable(),
            checkedAt: z.number().nullable(),
            listsUpdatedAt: z.number().nullable(),
            rebootRequired: z.boolean(),
            rebootPackages: z.array(z.string()),
            packages: z.array(z.object({
                name: z.string(),
                currentVersion: z.string(),
                candidateVersion: z.string(),
                origin: z.string(),
                security: z.boolean()
            })),
            error: z.string().nullable()
        }),
        zitadel: z.object({
            latestVersion: z.string().nullable(),
            latestPublishedAt: z.string().nullable(),
            latestUrl: z.string().nullable(),
            checkedAt: z.number().nullable(),
            error: z.string().nullable(),
            instanceVersions: z.array(z.object({
                version: z.string(),
                count: z.number()
            })),
            updateAvailable: z.boolean().nullable()
        })
    })
});

export const zGetAdminAuditQuery = z.object({
    limit: z.int().gte(1).lte(1000).optional().default(500),
    offset: z.int().gte(0).lte(9007199254740991).optional().default(0),
    order: z.enum(['newest', 'oldest']).optional().default('newest'),
    searchString: z.string().min(3).optional(),
    action: z.string().min(1).max(64).optional(),
    instanceId: z.string().min(1).max(64).optional()
});

/**
 * Audit log retrieved successfully
 */
export const zGetAdminAuditResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Audit log retrieved successfully'),
    data: z.object({
        total: z.number(),
        items: z.array(z.object({
            id: z.int().gte(-9007199254740991).lte(9007199254740991),
            actor_sub: z.string(),
            action: z.string(),
            target_instance_id: z.string().nullable(),
            detail: z.string().nullable(),
            created_at: z.int().gte(-9007199254740991).lte(9007199254740991)
        }))
    })
});

export const zGetAdminTasksQuery = z.object({
    limit: z.int().gte(1).lte(500).optional().default(200)
});

/**
 * Tasks retrieved successfully
 */
export const zGetAdminTasksResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Tasks retrieved successfully'),
    data: z.array(z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        function: z.string(),
        created_by_user_sub: z.string().nullable(),
        args: z.record(z.string(), z.unknown()),
        storeLogs: z.boolean(),
        status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        finished_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable(),
        result: z.record(z.string(), z.unknown()).nullable(),
        message: z.string().nullable()
    }))
});

export const zGetAdminTasksByTaskIdPath = z.object({
    taskId: z.int().gt(0).lte(9007199254740991)
});

/**
 * Task retrieved successfully
 */
export const zGetAdminTasksByTaskIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Task retrieved successfully'),
    data: z.object({
        id: z.int().gte(-9007199254740991).lte(9007199254740991),
        function: z.string(),
        created_by_user_sub: z.string().nullable(),
        args: z.record(z.string(), z.unknown()),
        storeLogs: z.boolean(),
        status: z.enum([
            'pending',
            'running',
            'paused',
            'failed',
            'completed'
        ]),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        finished_at: z.int().gte(-9007199254740991).lte(9007199254740991).nullable(),
        result: z.record(z.string(), z.unknown()).nullable(),
        message: z.string().nullable(),
        logs: z.string().nullable()
    })
});

/**
 * Sessions retrieved successfully
 */
export const zGetAdminSessionsResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Sessions retrieved successfully'),
    data: z.array(z.object({
        id: z.string(),
        user_sub: z.string(),
        user_email: z.string().nullable(),
        user_name: z.string().nullable(),
        user_role: z.enum(['admin', 'member']),
        login_method: z.enum(['oidc', 'static']),
        created_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        expires_at: z.int().gte(-9007199254740991).lte(9007199254740991),
        current: z.boolean()
    }))
});

export const zDeleteAdminSessionsBySessionIdPath = z.object({
    sessionId: z.string().min(1).max(128)
});

/**
 * Session revoked successfully
 */
export const zDeleteAdminSessionsBySessionIdResponse = z.object({
    success: z.literal(true),
    code: z.literal(200),
    message: z.literal('Session revoked successfully'),
    data: z.null()
});
